version: "3.8"

services:

  infra:
    image: localstack/localstack:2.0.1
    expose:
      - 4566

  setup:
    image: amazon/aws-cli:2.11.12
    entrypoint: /bin/sh -c
    command: >
      "aws sns create-topic --name scrape-artirst --endpoint-url http://infra:4566"
    environment:
      - AWS_ACCESS_KEY_ID=fake-id
      - AWS_SECRET_ACCESS_KEY=fake-secret
      - AWS_DEFAULT_REGION=sa-east-1
    depends_on:
      - infra

  scrape_trigger:
    image: scrape-trigger:latest
    environment:
      - WAIT_HOSTS=infra:4566
      - WAIT_AFTER=5
      - AWS_ACCESS_KEY_ID=fake-id
      - AWS_SECRET_ACCESS_KEY=fake-secret
      - AWS_DEFAULT_REGION=sa-east-1
      - SNS_ENDPOINT_URL=http://infra:4566
      - SNS_TOPIC_ARN=arn:aws:sns:sa-east-1:000000000000:scrape-artirst
    depends_on:
      - setup
