version: "3.8"

services:

  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    expose:
      - 5432

  migrations:
    image: batch-database-update:latest
    environment:
      - WAIT_HOSTS=postgres:5432
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=database
    volumes:
      - ./alembic.ini:/app/alembic.ini
      - ./migrations/:/app/migrations/
    depends_on:
      - postgres

  batch_database_update:
    image: batch-database-update:latest
    environment:
      - WAIT_HOSTS=postgres:5432
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=database
    depends_on:
      - postgres
