name: CI Test

on:
  push:
    paths:
      - libs/**
    branches-ignore:
      - main

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:

      - name: Echo
        run: echo "Hello World!"
