name: Libs - Database Tools

on:
  pull_request:

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            package:
              - 'libs/database-tools/**'

      - name: hello world
        if: steps.filter.outputs.package == 'true'
        run: echo "I have changed!"
