name: Libs - Database Tools

on:
  pull_request:

jobs:

  check_changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.filter.outputs.package }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            package:
              - 'libs/database-tools/**'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [check_changes]
    if: ${{ needs.check_changes.outputs.has_changes == 'true' }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: echo "I am building!"
