name: Continuous Deployment

on:
  pull_request:

# on:
#   push:
#     tags:
#      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:

  check_changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_changes.outputs.any_changed }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          echo "I'm here."
