name: Changelog Changes

on:
  push:
    # branches:
    #   - main

jobs:

  add_changes:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: print logs 1
        run: |
          git tag

      - name: Fetch tags
        run: |
          git fetch --tags origin

      - name: print logs 2
        run: |
          git tag

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Commitizen
        run: |
          pip install commitizen==2.38.0

      - name: Update changelog
        run: |
          cz changelog

      - name: Print changelog
        run: |
          cat CHANGELOG.md

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: Auto-update the changelog"
          file_pattern: "CHANGELOG.md"
