name: Changelog

on:
  push:
    branches:
      - main
    tags:
    # production ready versions (e.g. v1.0.0)
     - v[0-9]+.[0-9]+.[0-9]+

jobs:

  update_changelog:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Commitizen
        run: |
          pip install commitizen==2.38.0

      - name: Update changelog
        run: |
          cz changelog

      - name: Get commit SHA
        id: get_commit_sha
        run: |
          echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: Auto-update changelog (${{ steps.get_commit_sha.outputs.commit_sha }})"
          file_pattern: "CHANGELOG.md"
