name: Base CI

on:
  workflow_call:

    inputs:
      package_path:
        required: true
        type: string

jobs:

  check_changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_changes.outputs.any_changed }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List dependencies
        id: list_dependencies
        run: |
          PACKAGE_PATH=${{ inputs.package_path }}/**
          DEPENDENCIES_PATH=$(
            grep -o '"\.\./.*"' ${{ inputs.package_path }}/pyproject.toml |
            sed -e 's#"##g' -e 's#\.\./##g' -e 's#$#/**#g' |
            tr '\n' ',' |
            sed -e 's#,$##g'
          )
          echo "folders=$PACKAGE_PATH,$DEPENDENCIES_PATH" >> $GITHUB_OUTPUT

      - name: Check changes
        id: check_changes
        uses: tj-actions/changed-files@v33
        with:
          files: ${{ steps.list_dependencies.outputs.folders }}
          files_separator: ","

  ci:
    name: CI
    runs-on: ubuntu-latest
    needs: [check_changes]
    if: ${{ needs.check_changes.outputs.has_changes == 'true' }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.1
          virtualenvs-create: false

      - name: Build
        run: |
          make -C ${{ inputs.package_path }} build

      - name: Lint
        run: |
          make -C ${{ inputs.package_path }} lint

      - name: Test
        run: |
          make -C ${{ inputs.package_path }} test
