name: Continuous Integration

# on:
#   pull_request:

on:
  push:
    tags:
     - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:

  infra:
    uses: luizmanke/forgotify/.github/workflows/ci-base.yml@main
    with:
      package_path: infra

  pipelines:
    uses: luizmanke/forgotify/.github/workflows/ci-base.yml@main
    with:
      package_path: pipelines

  libs_database_tools:
    uses: luizmanke/forgotify/.github/workflows/ci-base.yml@main
    with:
      package_path: libs/database-tools

  libs_media_tools:
    uses: luizmanke/forgotify/.github/workflows/ci-base.yml@main
    with:
      package_path: libs/media-tools

  projects_batch_database_update:
    uses: luizmanke/forgotify/.github/workflows/ci-base.yml@main
    with:
      package_path: projects/batch-database-update
