name: Base Continuous Integration

on:
  workflow_call:

    inputs:
      package_path:
        required: true
        type: string

jobs:

  check_changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_changes.outputs.any_changed }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List dependencies
        id: list_dependencies
        run: |
          dependencies_path=$(./scripts/list_package_dependencies.sh ${{ inputs.package_path }})
          dependencies_wildcard=$(./scripts/join_paths_with_wildcard.sh ${{ inputs.package_path }} $dependencies_path)
          echo "folders=$dependencies_wildcard" >> $GITHUB_OUTPUT

      - name: Check changes
        id: check_changes
        uses: tj-actions/changed-files@v33
        with:
          files: ${{ steps.list_dependencies.outputs.folders }}
          files_separator: ","

  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    needs: [check_changes]
    if: ${{ needs.check_changes.outputs.has_changes == 'true' }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          make -C ${{ inputs.package_path }} build

      - name: Lint
        run: |
          make -C ${{ inputs.package_path }} lint

      - name: Test
        run: |
          make -C ${{ inputs.package_path }} test
